name: Build

on:
  push:
    branches: [master,dev]

jobs:

  build:
    runs-on: [ubuntu-latest]
    container: ubuntu:focal

    steps:
    - uses: actions/checkout@v4
    - name: Add download.mono-project.com/repo/ubuntu
      run: >
        apt-get update && apt-get install -y gnupg ca-certificates &&
        echo "deb http://download.mono-project.com/repo/ubuntu vs-focal main" > /etc/apt/sources.list.d/mono.list &&
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A6A19B38D3D831EF &&
        apt-get update
    - name: Install OS dependencies
      run: 'apt-get install -y --no-install-recommends git patch curl zip unzip mono-complete msbuild nuget'
    - name: Get ILSpy
      working-directory: /tmp
      run: 'git clone https://github.com/icsharpcode/ILSpy.git'
    - name: Build ILSpy
      run: './build-decompiler.sh'
    - name: Build
      run: 'msbuild /p:Configuration=Release'
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ILSpyConvert
        path: bin/Release
